java_version: "11"

kafka_version: "3.5.1"
kafka_install_dir: "/opt/kafka"
kafka_data_dir: "/var/lib/kafka"
kafka_log_dir: "/var/log/kafka"

zookeeper_version: "3.8.0"
zookeeper_install_dir: "/opt/zookeeper"
zookeeper_data_dir: "/var/lib/zookeeper"
