- name: Download and extract Kafka
  get_url:
    url: https://downloads.apache.org/kafka/{{ kafka_version }}/kafka_2.13-{{ kafka_version }}.tgz
    dest: /tmp/kafka.tgz

- name: Extract Kafka
  unarchive:
    src: /tmp/kafka.tgz
    dest: "{{ kafka_install_dir }}"
    remote_src: yes

- name: Configure Kafka
  template:
    src: server.properties.j2
    dest: "{{ kafka_install_dir }}/config/server.properties"

- name: Start Kafka
  shell: "{{ kafka_install_dir }}/bin/kafka-server-start.sh -daemon {{ kafka_install_dir }}/config/server.properties"
