- name: Download and extract ZooKeeper
  get_url:
    url: https://downloads.apache.org/zookeeper/zookeeper-{{ zookeeper_version }}/apache-zookeeper-{{ zookeeper_version }}-bin.tar.gz
    dest: /tmp/zookeeper.tar.gz

- name: Extract ZooKeeper
  unarchive:
    src: /tmp/zookeeper.tar.gz
    dest: "{{ zookeeper_install_dir }}"
    remote_src: yes

- name: Configure ZooKeeper
  template:
    src: zoo.cfg.j2
    dest: "{{ zookeeper_install_dir }}/conf/zoo.cfg"

- name: Start ZooKeeper
  shell: "{{ zookeeper_install_dir }}/bin/zkServer.sh start"
