- name: Install Java
  apt:
    name: openjdk-{{ java_version }}-jdk
    state: present

- name: Create necessary directories
  file:
    path: "{{ item }}"
    state: directory
    owner: kafka
    group: kafka
    mode: '0755'
  with_items:
    - "{{ kafka_install_dir }}"
    - "{{ kafka_data_dir }}"
    - "{{ kafka_log_dir }}"
    - "{{ zookeeper_install_dir }}"
    - "{{ zookeeper_data_dir }}"
